config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  resources :category_products
  resources :bill_receivables
  resources :bill_payables
  resources :provider_contracts
  resources :banks
  resources :cred_cards
  resources :revenues
  resources :categories
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :transfers, except: %i[edit update]

  # resources :out_of_stocks
  resources :delivery_options
  resources :type_of_payments
  resources :products
  resources :budgets
  resources :hits
  resources :providers
  resources :clients
  resources :employees
  resources :stock_raw_materials, except: %i[edit update]
  resources :stock_final_products
  resources :compositions
  resources :raw_materials

  # client_product_custom
  get '/clients/:id/create_product_customs', to: 'clients#create_product_customs'
  get '/clients/:id/product_customs', to: 'clients#list_product_customs'
  put '/clients/:id/product_customs_update', to: 'clients#update_list_product_customs'

  # credito / debito
  get '/bank/credit_or_debit/:id', to: 'banks#credit_or_debit', as: :credit_or_debit
  post '/bank/credit_or_debit/:id', to: 'banks#credit_or_debit_update', as: :credit_or_debit_update

  # contas a receber
  put '/contas_a_receber/item/receber/:item_id', to: 'bill_receivables#receive_item_update', as: :receive_item_update
  get '/contas_a_receber/item/receber/:item_id', to: 'bill_receivables#receive_item', as: :receive_item

  post '/contas_a_receber/receber_itens', to: 'bill_receivables#receives', as: :receives
  put '/contas_a_receber/receber_itens', to: 'bill_receivables#receives_update', as: :receives_update

  # contas a pagar
  get '/payment/excel/', to: 'bill_payables#payment_excel', as: :excel
  put '/contas_a_pagar/item/pagar/:item_id', to: 'bill_payables#pay_item_update', as: :pay_item_update
  get '/contas_a_pagar/item/pagar/:item_id', to: 'bill_payables#pay_item', as: :pay_item

  post '/contas_a_pagar/paga_itens', to: 'bill_payables#pays', as: :pays
  put '/contas_a_pagar/paga_itens', to: 'bill_payables#pays_update', as: :pays_update

  get '/product/cod/:cod', to: 'products#product_cod', as: :product_cod

  put '/reserve_product/:id' => 'budgets#updated_reserve_product', as: :reserve_product

  get '/reserve_all_budget/:id' => 'budgets#reserve_all_budget', as: :reserve_all_budget

  scope '/relatorio' do
    get '/producao-diaria' => 'reports#daily_production', as: :daily_production
  end

  scope '/busca' do
    get '/endereco/:cep', to: 'home#find_by_address'
    get '/cidades/:id', to: 'home#find_city'
    get '/sub-item-entrega/:id', to: 'home#find_delivery'
    get '/sub-item-pagamento/:id', to: 'home#find_payment'
    get '/batida/:id', to: 'home#find_hit'
    get '/produto-primitivo/:id', to: 'home#produto_primitivo'
  end

  scope '/pedido' do
    get '/reserve_product/:id', to: 'budgets#reserve_product'
    get '/pdf/:id', to: 'budgets#budget_pdf', as: :budget_pdf
    get '/orderm-de-servico/:id', to: 'budgets#order_service', as: :order_service
    get '/atualiza-status/:id/:status', to: 'budgets#update_status', as: :budget_update_status
    post '/atualiza-status/', to: 'budgets#update_status', as: :budget_update_status_obs
  end

  get '/load_hit_items/:composition', to: 'hits#load_items'
  get '/find_product/:id', to: 'budgets#find_product'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  root to: 'home#index'
end

app/models/bill_receivable.rb
class BillReceivable < ApplicationRecord
  acts_as_paranoid

  enum status: { pending: 0, late: 1, paid: 2 }
  enum type_receivable: { budget: 0, other: 1 }

  mount_uploader :file, FilesUploader

  belongs_to :budget, -> { with_deleted }, optional: true
  belongs_to :category, -> { with_deleted }, optional: true
  belongs_to :revenue, -> { with_deleted }, optional: true

  has_many :bill_receivable_installments, dependent: :destroy

  accepts_nested_attributes_for :bill_receivable_installments, allow_destroy: true

  has_paper_trail

  validates :bill_receivable_installments, presence: true
  validates :total_value, numericality: { greater_than: 0 }

  validates :budget, presence: true, if: :budget?

  validates :name_other, presence: true, if: :other?
  validates :phone_other, presence: true, if: :other?

  validates_presence_of :cpf_other, :unless => :cpf?
  validates_presence_of :cnpj_other, :unless => :cnpj?

  before_create :set_due_date_and_status
  before_update :due_date_verify

  after_update :set_value

  def due_date_verify
    data = []
    check = true
    self.bill_receivable_installments.map do |e|
      if e.status == 'pending'
        data << e.date
        check = false
      end
    end
    if data.present?
      self.due_date = data.sort.first
      if self.due_date < Date.today
        self.status = 1
      else
        self.status = 0
      end
    else
      if check
        self.status = 2
      end
    end
  end

  def set_due_date_and_status
    data = []
    self.bill_receivable_installments.map { |e| data << e.date }
    self.due_date = data.sort.first
    if self.due_date < Date.today
      self.status = 1
    else
      self.status = 0
    end
  end

  private

    def set_value
      total_bill = self.total_value.round(2)
      value_item = self.bill_receivable_installments.sum(:value).round(2)
      interest_item = self.bill_receivable_installments.sum(:interest).round(2)
      ActiveRecord::Base.transaction do
        unless total_bill == value_item
          self.update total_value: value_item
        end
        unless self.interest == interest_item
          self.update interest: interest_item
        end
      end
    end

    def other?
      self.type_receivable == 'other'
    end

    def budget?
      self.type_receivable == 'budget'
    end

    def cpf?
      self.cnpj_other.present? or !other?
    end

    def cnpj?
      self.cpf_other.present? or !other?
    end
end

app/controllers/bill_receivables_controller.rb
class BillReceivablesController < ApplicationController
  before_action :set_bill_receivable, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /bill_receivables
  # GET /bill_receivables.json
  def index
    @q = BillReceivable.ransack(params[:q])

    @bill_receivables = @q.result.includes(:category, :revenue, :budget).accessible_by(current_ability).order(id: :desc).page params[:page]
    @modal_size = 'lg'

  end

  def receives
    @receives = BillReceivableInstallment.where(id: params[:receber])
    # render json: {receives: @receives.pluck(:id), count: @receives.size}
  end

  def receives_update
    receives = params[:receives]
    @receives = BillReceivableInstallment.update(receives.keys, receives.values)
    aux = true
    @receives.each do |e|
      if e.errors.present?
        aux = false
      end
    end
    if aux
      redirect_to bill_receivables_url, success: 'Parcelas pagas com sucesso.'
    else
      render :receives
    end
  end

  def receive_item
    @receive = BillReceivableInstallment.find(params[:item_id])
    @bill_receivable = @receive.bill_receivable
    if params[:modal] == 'true'
      @modal = true
      render :receive_item, layout: false
    end
  end

  def receive_item_update
    @receive = BillReceivableInstallment.find(params[:item_id])
    @bill_receivable = @receive.bill_receivable
    @modal = true
    @bill_receivable.update(bill_receivable_params)
  end

  # GET /bill_receivables/1
  # GET /bill_receivables/1.json
  def show
    if params[:modal] == 'true'
      @modal = true
      render :show, layout: false
    end
  end

  # GET /bill_receivables/new
  def new
    @bill_receivable = BillReceivable.new
    @bill_receivable.bill_receivable_installments.build
  end

  # GET /bill_receivables/1/edit
  def edit
  end

  # POST /bill_receivables
  # POST /bill_receivables.json
  def create
    @bill_receivable = BillReceivable.new(bill_receivable_params)

    respond_to do |format|
      if @bill_receivable.save
        format.html { redirect_to @bill_receivable, notice: 'Conta a receber criada com sucesso.' }
        format.json { render :show, status: :created, location: @bill_receivable }
      else
        format.html { render :new }
        format.json { render json: @bill_receivable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bill_receivables/1
  # PATCH/PUT /bill_receivables/1.json
  def update
    respond_to do |format|
      if @bill_receivable.update(bill_receivable_params)
        format.html { redirect_to @bill_receivable, notice: 'Conta a receber atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @bill_receivable }
      else
        format.html { render :edit }
        format.json { render json: @bill_receivable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bill_receivables/1
  # DELETE /bill_receivables/1.json
  def destroy
    @bill_receivable.destroy
    respond_to do |format|
      format.html { redirect_to bill_receivables_url, notice: 'Conta a receber apagada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill_receivable
      @bill_receivable = BillReceivable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_receivable_params
      params.require(:bill_receivable).permit!
    end
end

app/helpers/bill_receivables_helper.rb
module BillReceivablesHelper
  def label_status_br(bill_receivable)
    # pending: 0, late: 1, paid: 2
    # bill_receivable.status_i18n
    status = bill_receivable.status

    bill_receivable.due_date_verify

    if status != bill_receivable.status
      bill_receivable.save
      status = bill_receivable.status
    end
    aux = ''
    text = t "enums.bill_receivable.status.#{status}"

    case status
    when 'paid'
      aux = "<span class='badge badge-success' style='font-size:14px;'>#{text}</span>"
    when 'pending'
      aux = "<span class='badge badge-warning' style='font-size:14px;'>#{text}</span>"
    when 'late'
      aux = "<span class='badge badge-danger' style='font-size:14px;'>#{text}</span>"
    end
    return aux.html_safe
  end

  def label_status_bri(bill_receivable_installment)
    # pending: 0, late: 1, paid: 2
    # bill_receivable.status_i18n
    bill_receivable = bill_receivable_installment.bill_receivable
    status_bill = bill_receivable.status

    bill_receivable.due_date_verify

    if status_bill != bill_receivable.status
      bill_receivable.save
    end

    status = bill_receivable_installment.status
    if bill_receivable_installment.date < Date.today and status != "paid"
      status = "late"
    end

    aux = ''
    text = t "enums.bill_receivable_installment.status.#{bill_receivable_installment.status}"

    case status
    when 'paid'
      aux = "<span class='badge badge-success' style='font-size:14px;'>#{text}</span>"
    when 'pending'
      aux = "<span class='badge badge-warning' style='font-size:14px;'>#{text}</span>"
    when 'late'
      aux = "<span class='badge badge-danger' style='font-size:14px;'>#{text}</span>"
    end
    return aux.html_safe
  end
end

app/views/bill_receivables/_bill_receivable_item.html.erb
<%- model_class = BillReceivable -%>
<td scope="row"><%= link_to bill_receivable.id, bill_receivable %></td>
<td>
  <% if bill_receivable.type_receivable == 'budget' %>
    <%= link_to_modal bill_receivable.budget.cod_name, budget_path(bill_receivable.budget), class: 'text-dark' %>
  <% else %>
    <ul class="list-unstyled">
      <li>
        <strong>
          <%= model_class.human_attribute_name(:name_other) %>:
        </strong>
        <%= bill_receivable.name_other %>
      </li>
      <li>
        <strong>
          <%= model_class.human_attribute_name(:cpf_other) %>/<%= model_class.human_attribute_name(:cnpj_other) %>:
        </strong>
        <%= bill_receivable.cpf_other.present? ? bill_receivable.cpf_other : bill_receivable.cnpj_other %>
      </li>
      <li>
        <strong>
          <%= model_class.human_attribute_name(:phone_other) %>:
        </strong>
        <%= bill_receivable.phone_other %>
      </li>
    </ul>
  <% end %>
</td>
<td><%= bill_receivable.category.try(:name) %></td>
<td><%= bill_receivable.revenue.try(:name) %></td>
<td><%= label_status_bri bill_receivable_installment %></td>
<td><%= number_to_currency bill_receivable_installment.value %></td>
<td><%= bill_receivable_installment.status != 'paid' ? bill_receivable_installment.date : '-' %></td>
<% if bill_receivable_installment.status != 'paid' %>
  <td class="d-print-none text-center" onclick="change_check_pay('pay_<%= bill_receivable_installment.id %>');">
    <%= check_box_tag "receber[]", bill_receivable_installment.id, false , :class=>"styled d-none", id: "pay_#{bill_receivable_installment.id}" %>
    <i class="material-icons " id="check_pay_<%= bill_receivable_installment.id %>">
      check_box_outline_blank
    </i>
  </td>
<% else %>
  <td>-</td>
<% end %>
<td class="d-print-none text-center">
  <%= link_to_modal_form "Receber", receive_item_path(bill_receivable_installment), class: 'btn btn-outline-success' if bill_receivable_installment.status != 'paid' %>
  <%#= link_to bill_receivable, class: 'btn btn-info has-icon' do %>
  <!-- <i class="material-icons">remove_red_eye</i> -->
  <%#= t('.show', :default => t("helpers.links.show")) %>
  <%# end %>
  <%= link_to edit_bill_receivable_path(bill_receivable), class: 'btn btn-primary has-icon' do %>
  <!-- <i class="material-icons">edit</i> -->
  <%= t('.edit', :default => t("helpers.links.edit")) %>
  <% end %>
  <%= link_to bill_receivable, method: :delete, data: { confirm: t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, class: 'btn btn-danger has-icon' do %>
  <!-- <i class="material-icons">delete</i> -->
  <%= t('.destroy', :default => t("helpers.links.destroy")) %>
  <% end %>
</td>

app/views/bill_receivables/_receive_item.html.erb
<%= simple_nested_form_for(@bill_receivable, :url => receive_item_update_path(@receive.id), :method => :put, remote: @modal) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <% if @bill_receivable.errors[:bill_receivable_installments].present? %>
    <legend class="alert alert-danger">
      <small class=""><%= @bill_receivable.errors.full_messages.first %></small>
    </legend>
  <% end %>
  <div id="bill_receivable_installments">
    <%= f.fields_for :bill_receivable_installments do |bill_receivable_installments_form| %>
      <% if bill_receivable_installments_form.object.id == @receive.id %>
        <div class="card card-body mb-3">
          <div class="row">
            <div class="col-lg-8">
              <span class="change_icon_file">
                <span class="badge badge-success file-name"><%= bill_receivable_installments_form.object.file.file.identifier if bill_receivable_installments_form.object.file.present? %></span>
                <div class="d-flex flex-row bd-highlight mb-3">
                  <i class="material-icons p-2 bd-highlight">
                  <span class="icon-file badge <%= bill_receivable_installments_form.object.file.present? ? 'badge-success' : 'badge-danger' %> ">
                    <%= bill_receivable_installments_form.object.file.present? ? 'cloud_done' : 'cloud' %>
                  </span>
                  </i>
                  <%= bill_receivable_installments_form.input :file, label: false, input_html: { class: 'p-2 bd-highlight update_file_by_icon', onchange: "change_icon_file($(this));" } %>
                </div>
                <%= bill_receivable_installments_form.hidden_field :file_cache %>

              </span>
            <script>
              $('.datepicker-here').datepicker({

                  minDate: new Date() // Now can select only dates, which goes after today
              })
            </script>
            <style>
              .datepicker{z-index:1151 !important;}
            </style>
              <%= bill_receivable_installments_form.input :payday, as: :string, required: false, input_html: { class: 'date datepicker-here', data: { language: 'pt-BR'}, value: Date.today } %>
              <%= bill_receivable_installments_form.input :status, as: :hidden, input_html: { value: 'paid' } %>
              <%= bill_receivable_installments_form.input :interest %>
              <%= hidden_field_tag :modal, @modal  %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <hr>
  <%= f.button :submit, "Receber", class: 'btn btn-success ' %>
<% end %>

app/views/bill_receivables/_search.html.erb
<%- model_class = BillReceivable -%>
<%= search_form_for @q, url: bill_receivables_path, html: { class: 'form-horizonal d-print-none' } do |f| %>
  <h3>Busca</h3>
  <div class="row justify-content-md-center">
    <div class="col-4">
      <%= f.input :budget_cod_name_or_name_other_cont, label: model_class.human_attribute_name(:type_receivable), placeholder: 'Ex: 434/2018', required: false %>
      <%= f.input :status_eq, label: model_class.human_attribute_name(:status), as: :select, placeholder: 'code', :as => :select, :collection => BillReceivable.statuses.map {|x| [t("enums.bill_receivable.status.#{x[0]}"), x[1]]}.sort_by {|a,b| a }, :include_blank => "Todas", input_html: {class: 'simple-select2'}, required: false %>
    </div> 
    <div class="col-4">
      <%= f.input :bill_receivable_installments_date_gteq, label: "#{model_class.human_attribute_name(:bill_receivable_installments_date)} inicial", as: :string, placeholder: 'Ex: 10/01/2018', required: false, input_html: { class: 'date datepicker-here', data: { language: 'pt-BR'} } %>
      <%= f.input :bill_receivable_installments_date_lteq, label: "#{model_class.human_attribute_name(:bill_receivable_installments_date)} final", as: :string, placeholder: 'Ex: 10/02/2018', required: false, input_html: { class: 'date datepicker-here', data: { language: 'pt-BR'} } %>
    </div>
    <div class="col-4">,
    </div>
    <%= f.button :submit, class: 'btn btn-success' %>
    <%= link_to 'Limpar', bill_receivables_path, class: 'btn btn-info ml-3' %>
  </div>
  <hr>
<% end %>

app/views/bill_receivables/edit.html.erb
<%- model_class = BillReceivable -%>
<div class="page-header d-flex justify-content-lg-between align-items-center">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render 'form', bill_receivable: @bill_receivable %>

app/views/bill_receivables/index.html.erb
<%- model_class = BillReceivable -%>
<div class="page-header d-flex justify-content-lg-between align-items-center">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <%= link_to t('.new', :default => t("helpers.links.new")), new_bill_receivable_path, class: "btn btn-primary d-print-none" %>
</div>
<%= render 'search' %>

<%= form_tag receives_path do %>
  <div class="d-flex justify-content-between w-100">
    <div class="mb-2">
      <%= paginate @bill_receivables if @bill_receivables.size > 20 %>
      <%= page_entries_info @bill_receivables, entry_name: 'item' %>
    </div>
    <div class="mb-2">
      <%= link_to "Selecionar todos", "javascript:;", :id => "select_all", :class => 'btn btn-info d-print-none' -%>
      <%= submit_tag "Receber selecionados", :class => 'btn btn-success d-print-none pay_all', disabled: true %>
    </div>
  </div>
<%= paginate @bill_receivables %>
  <div class="table-responsive">
    <table class="table table-bordered table-hover text-center">
      <thead class="thead-light">
        <tr>
          <th scope="col"><%= sort_link @q, :id, "#", default_order: :desc %></th>

          <th scope="col"><%= sort_link @q, :type_receivable, model_class.human_attribute_name(:type_receivable), default_order: :desc %></th>
          <th scope="col"><%= sort_link @q, :category, model_class.human_attribute_name(:category), default_order: :desc %></th>
          <th scope="col"><%= sort_link @q, :revenue, model_class.human_attribute_name(:revenue), default_order: :desc %></th>
          <th scope="col"><%= sort_link @q, :status, model_class.human_attribute_name(:status), default_order: :desc %></th>
          <th scope="col"><%= sort_link @q, :total_value, "Valor", default_order: :desc %></th>
          <th scope="col"><%= sort_link @q, :total_value, model_class.human_attribute_name(:due_date), default_order: :desc %></th>
          <th scope="col" class="d-print-none text-center">Selecione</th>
          <th scope="col" class="d-print-none text-center"><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>

      <tbody>
        <% @bill_receivables.includes(:bill_receivable_installments).each do |bill_receivable| %>
          <% bill_receivable.bill_receivable_installments.each do |bill_receivable_installment| %>
            <tr id="bill_receivable-item-<%= bill_receivable_installment.id %>">
              <%= render 'bill_receivable_item', bill_receivable: bill_receivable, bill_receivable_installment: bill_receivable_installment %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

<%= paginate @bill_receivables %>

app/views/bill_receivables/new.html.erb
<%- model_class = BillReceivable -%>
<div class="page-header d-flex justify-content-lg-between align-items-center">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<%= render 'form', bill_receivable: @bill_receivable %>

app/views/bill_receivables/receive_item.html.erb
<div class="page-header d-flex justify-content-lg-between align-items-center">
  <h3>Parcela de <%= @receive.date %> </h3>
</div>
<legend>Valor: <%= number_to_currency @receive.value %></legend>


<span class="new_form_remote">
  <%= render 'receive_item', bill_receivable: @bill_receivable, receive: @receive, modal: @modal %>
</span>

app/views/bill_receivables/show.html.erb
<%- model_class = BillReceivable -%>


<div class="page-header d-flex flex-row justify-content-start align-items-center w-100">
  <h1><strong><%=t '.title', :default => model_class.model_name.human.titleize %></strong></h1>
  <% unless @modal %>
    <div class="d-flex flex-row justify-content-start align-items-center ml-auto">
    <%= link_to t('.new', :default => t("helpers.links.new")), new_bill_receivable_path, class: "btn btn-info" %>
    <%= link_to t('.back', :default => t("helpers.links.back")),
                bill_receivables_path, :class => 'btn btn-secondary ml-2'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_bill_receivable_path(@bill_receivable), :class => 'btn btn-primary ml-2' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  bill_receivable_path(@bill_receivable),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger ml-2' %>
    </div>
  <% end %>
</div>

<div class="row mt-4 mb-4">
  <div class="col-6">
    <p>
      <% if @bill_receivable.type_receivable == 'budget' %>
        <strong>
          <%= model_class.human_attribute_name(:budget) %>:
        </strong>
        <%= link_to_modal @bill_receivable.budget.cod_name, budget_path(@bill_receivable.budget), class: "text-dark" %>
        <hr>
      <% else %>
        <strong>
          <%= model_class.human_attribute_name(:name_other) %>:
        </strong>
        <%= @bill_receivable.name_other %>
        <hr>

        <strong>
          <%= model_class.human_attribute_name(:cpf_other) %>/<%= model_class.human_attribute_name(:cnpj_other) %>:
        </strong>
        <%= @bill_receivable.cpf_other.present? ? @bill_receivable.cpf_other : @bill_receivable.cnpj_other %>
        <hr>

        <strong>
          <%= model_class.human_attribute_name(:phone_other) %>:
        </strong>
        <%= @bill_receivable.phone_other %>
        <hr>

        <strong>
          <%= model_class.human_attribute_name(:obs_other) %>:
        </strong>
        <%= @bill_receivable.obs_other %>
        <hr>
      <% end %>

      <strong>
        <%= model_class.human_attribute_name(:total_value) %>:
      </strong>

      <%= number_to_currency @bill_receivable.total_value %>
      <hr>

      <strong>
        <%= model_class.human_attribute_name(:status) %>:
      </strong>

      <%= label_status_br @bill_receivable %>
      <hr>
      <strong>
        <%= model_class.human_attribute_name(:file) %>:
      </strong>

      <%= link_to @bill_receivable.file_identifier, @bill_receivable.file.url, download: @bill_receivable.file_identifier if @bill_receivable.file.present? %>
      <hr>
    </p>
  </div>
  <div class="col-6">
    <p>
      <strong>
        <%= model_class.human_attribute_name(:category) %>:
      </strong>

      <%= @bill_receivable.category.try(:name) %>
      <hr>

      <strong>
        <%= model_class.human_attribute_name(:revenue) %>:
      </strong>

      <%= @bill_receivable.revenue.try(:name) %>
      <hr>

      <strong>
        <%= model_class.human_attribute_name(:obs) %>:
      </strong>

      <%= @bill_receivable.obs %>
      <hr>

    </p>
  </div>
</div>

<strong>
  <%= model_class.human_attribute_name(:bill_receivable_installments) %>:
</strong>
<%- model_class = BillReceivableInstallment -%>
<div class="table-responsive">
  <table class="table table-bordered table-hover text-center">
    <thead class="thead-light">
      <tr>
        <th scope="col"><%= model_class.human_attribute_name(:bank) %></th>
        <th scope="col"><%= model_class.human_attribute_name(:file) %></th>
        <th scope="col"><%= model_class.human_attribute_name(:file_to_pay) %></th>
        <th scope="col"><%= model_class.human_attribute_name(:status) %></th>
        <th scope="col"><%= model_class.human_attribute_name(:value) %></th>
        <th scope="col"><%= model_class.human_attribute_name(:interest) %></th>
        <th scope="col"><%= model_class.human_attribute_name(:date) %></th>
        <th scope="col"><%= model_class.human_attribute_name(:payday) %></th>
        <th scope="col" class="d-print-none text-center"><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>

    <tbody>
      <% @bill_receivable.bill_receivable_installments.includes(:bank).each do |bill_receivable_installment| %>
        <tr>
          <td>
            <%= bill_receivable_installment.bank.name %>
          </td>

          <td>
            <%= link_to bill_receivable_installment.file_identifier, bill_receivable_installment.file.url, download: bill_receivable_installment.file_identifier if bill_receivable_installment.file.present? %>
          </td>
          <td>
            <%= link_to bill_receivable_installment.file_to_pay_identifier, bill_receivable_installment.file_to_pay.url, download: bill_receivable_installment.file_to_pay_identifier if bill_receivable_installment.file_to_pay.present? %>
          </td>
          <td>
            <%= bill_receivable_installment.status_i18n %>
          </td>
          <td>
            <%= number_to_currency bill_receivable_installment.value %>
          </td>
          <td>
            <%= number_to_currency bill_receivable_installment.interest %>
          </td>
          <td>
            <%= bill_receivable_installment.date %>
          </td>
          <td>
            <%= bill_receivable_installment.payday %>
          </td>
          <td>
            -
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>