config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  resources :category_products
  resources :bill_receivables
  resources :bill_payables
  resources :provider_contracts
  resources :banks
  resources :cred_cards
  resources :revenues
  resources :categories
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :transfers, except: %i[edit update]

  # resources :out_of_stocks
  resources :delivery_options
  resources :type_of_payments
  resources :products
  resources :budgets
  resources :hits
  resources :providers
  resources :clients
  resources :employees
  resources :stock_raw_materials, except: %i[edit update]
  resources :stock_final_products
  resources :compositions
  resources :raw_materials

  # client_product_custom
  get '/clients/:id/create_product_customs', to: 'clients#create_product_customs'
  get '/clients/:id/product_customs', to: 'clients#list_product_customs'
  put '/clients/:id/product_customs_update', to: 'clients#update_list_product_customs'

  # credito / debito
  get '/bank/credit_or_debit/:id', to: 'banks#credit_or_debit', as: :credit_or_debit
  post '/bank/credit_or_debit/:id', to: 'banks#credit_or_debit_update', as: :credit_or_debit_update

  # contas a receber
  put '/contas_a_receber/item/receber/:item_id', to: 'bill_receivables#receive_item_update', as: :receive_item_update
  get '/contas_a_receber/item/receber/:item_id', to: 'bill_receivables#receive_item', as: :receive_item

  post '/contas_a_receber/receber_itens', to: 'bill_receivables#receives', as: :receives
  put '/contas_a_receber/receber_itens', to: 'bill_receivables#receives_update', as: :receives_update

  # contas a pagar
  get '/payment/excel/', to: 'bill_payables#payment_excel', as: :excel
  put '/contas_a_pagar/item/pagar/:item_id', to: 'bill_payables#pay_item_update', as: :pay_item_update
  get '/contas_a_pagar/item/pagar/:item_id', to: 'bill_payables#pay_item', as: :pay_item

  post '/contas_a_pagar/paga_itens', to: 'bill_payables#pays', as: :pays
  put '/contas_a_pagar/paga_itens', to: 'bill_payables#pays_update', as: :pays_update

  get '/product/cod/:cod', to: 'products#product_cod', as: :product_cod

  put '/reserve_product/:id' => 'budgets#updated_reserve_product', as: :reserve_product

  get '/reserve_all_budget/:id' => 'budgets#reserve_all_budget', as: :reserve_all_budget

  scope '/relatorio' do
    get '/producao-diaria' => 'reports#daily_production', as: :daily_production
  end

  scope '/busca' do
    get '/endereco/:cep', to: 'home#find_by_address'
    get '/cidades/:id', to: 'home#find_city'
    get '/sub-item-entrega/:id', to: 'home#find_delivery'
    get '/sub-item-pagamento/:id', to: 'home#find_payment'
    get '/batida/:id', to: 'home#find_hit'
    get '/produto-primitivo/:id', to: 'home#produto_primitivo'
  end

  scope '/pedido' do
    get '/reserve_product/:id', to: 'budgets#reserve_product'
    get '/pdf/:id', to: 'budgets#budget_pdf', as: :budget_pdf
    get '/orderm-de-servico/:id', to: 'budgets#order_service', as: :order_service
    get '/atualiza-status/:id/:status', to: 'budgets#update_status', as: :budget_update_status
    post '/atualiza-status/', to: 'budgets#update_status', as: :budget_update_status_obs
  end

  get '/load_hit_items/:composition', to: 'hits#load_items'
  get '/find_product/:id', to: 'budgets#find_product'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  root to: 'home#index'
end

app/models/composition.rb
class Composition < ApplicationRecord
  acts_as_paranoid

  has_many :compositionals, dependent: :destroy
  has_many :raw_materials, through: :compositionals
  belongs_to :type_residue, class_name: 'RawMaterial'

  accepts_nested_attributes_for :compositionals, allow_destroy: true

  has_paper_trail

  validates :name, presence: true
  validates :type_residue, presence: true
  validates :name, uniqueness: { :case_sensitive => false }
  validates :compositionals, presence: true

end

app/controllers/compositions_controller.rb
class CompositionsController < ApplicationController
  before_action :set_composition, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /compositions
  # GET /compositions.json
  def index
    @compositions = Composition.accessible_by(current_ability).order(id: :desc).page params[:page]
  end

  # GET /compositions/1
  # GET /compositions/1.json
  def show
    if params[:modal] == 'true'
      @modal = true
      render :show, layout: false
    end
  end

  # GET /compositions/new
  def new
    @composition = Composition.new
    @composition.compositionals.build
  end

  # GET /compositions/1/edit
  def edit
  end

  # POST /compositions
  # POST /compositions.json
  def create
    @composition = Composition.new(composition_params)

    respond_to do |format|
      if @composition.save
        format.html { redirect_to @composition, notice: 'Composição criado com sucesso.' }
        format.json { render :show, status: :created, location: @composition }
      else
        format.html { render :new }
        format.json { render json: @composition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compositions/1
  # PATCH/PUT /compositions/1.json
  def update
    respond_to do |format|
      if @composition.update(composition_params)
        format.html { redirect_to @composition, notice: 'Composição atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @composition }
      else
        format.html { render :edit }
        format.json { render json: @composition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compositions/1
  # DELETE /compositions/1.json
  def destroy
    @composition.destroy
    respond_to do |format|
      format.html { redirect_to compositions_url, notice: 'Composição apagada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_composition
      @composition = Composition.with_deleted.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def composition_params
      params.require(:composition).permit!
    end
end

app/helpers/compositions_helper.rb
module CompositionsHelper
end

app/views/compositions/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-8 col-sm-12">
      <%= simple_nested_form_for(@composition) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <% if @composition.errors.full_messages.any? %>
          <ul>
            <% @composition.errors.full_messages.each do |error_message| %>
              <li class="alert alert-danger">
                <%= error_message if @composition.errors.full_messages.first == error_message %> <br />
              </li>
            <% end %>
          </ul>
        <% end %>
        <div class="form-inputs">
          <%= f.input :name %>
          <%= f.association :type_residue, as: :select, collection: RawMaterial.order(:name).map { |e| [e.name, e.id] }, input_html: {class: 'simple-select2'}, wrapper_html: {class: 'w-100'} %>
        </div>
        <div id="compositionals">
          <%= f.fields_for :compositionals do |compositionals_form| %>
            <div class="card card-body">
              <div class="d-flex flex-row justify-content-start align-items-end">
                <%= compositionals_form.input :raw_material_id, as: :select, collection: RawMaterial.order(:name), input_html: {class: 'simple-select2'}, wrapper_html: {class: 'w-100'} %>
                <%= compositionals_form.link_to_remove "Remover composto", class: 'btn btn-outline-danger float-right mb-3 ml-2' %>
              </div>
            </div>
            <br>
          <% end %>
        </div>
        <hr>
        <p><%= f.link_to_add "Adicionar Composto", :compositionals, :data => { :target => "#compositionals" }, class: 'btn btn-outline-primary' %></p>
        <hr>
        <div class="form-actions">
          <%= f.button :submit, :class => 'btn btn-success' %>
          <%= link_to t('.cancel', :default => t("helpers.links.cancel")), compositions_path, :class => 'btn btn-danger' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/compositions/edit.html.erb
<%- model_class = Composition -%>
<div class="page-header d-flex justify-content-lg-between align-items-center">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render 'form', composition: @composition %>

app/views/compositions/index.html.erb
<%- model_class = Composition -%>
<div class="page-header d-flex justify-content-lg-between align-items-center">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <%= link_to t('.new', :default => t("helpers.links.new")), new_composition_path, class: "btn btn-primary" %>
</div>

<%= paginate @compositions if @compositions.size > 20 %>
<%= page_entries_info @compositions, entry_name: 'item' %>
<div class="table-responsive">
  <table class="table table-bordered table-hover text-center">
    <thead class="thead-light">
      <tr>
        <th scope="col">#</th>
        <th scope="col"><%= model_class.human_attribute_name(:name) %></th>
        <th scope="col"><%= model_class.human_attribute_name(:compositional) %>s</th>
        <th scope="col"><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @compositions.each do |composition| %>
      <tr>
        <td scope="row"><%= composition.id %></td>
        <td><%= composition.name %></td>
        <td><%= composition.raw_materials.size %></td>
        <td>
          <%= link_to composition, class: 'btn btn-info has-icon' do %>
            <i class="material-icons">remove_red_eye</i>
            <%#= t('.show', :default => t("helpers.links.show")) %>
          <% end %>
          <%= link_to edit_composition_path(composition), class: 'btn btn-primary has-icon' do %>
            <i class="material-icons">edit</i>
            <%#= t('.edit', :default => t("helpers.links.edit")) %>
          <% end %>
          <%= link_to composition, method: :delete, data: { confirm: t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, class: 'btn btn-danger has-icon' do %>
            <i class="material-icons">delete</i>
            <%#= t('.destroy', :default => t("helpers.links.destroy")) %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate @compositions %>

app/views/compositions/new.html.erb
<%- model_class = Composition -%>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-8 col-sm-12">
      <div class="page-header d-flex justify-content-lg-between align-items-center">
        <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
      </div>
    </div>
  </div>
</div>

<%= render 'form', composition: @composition %>

app/views/compositions/show.html.erb
<%- model_class = Composition -%>

<div class="page-header d-flex flex-row justify-content-start align-items-center w-100">
  <h1><strong><%=t '.title', :default => model_class.model_name.human.titleize %></strong></h1>
  <% unless @modal %>
    <div class="d-flex flex-row justify-content-start align-items-center ml-auto">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                compositions_path, :class => 'btn btn-secondary'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_composition_path(@composition), :class => 'btn btn-primary ml-2' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  composition_path(@composition),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger ml-2' %>
    </div>
  <% end %>
</div>

<div class="row mt-4 mb-4">
  <div class="col-6">
    <p>
      <strong>
        <%= model_class.human_attribute_name(:name) %>:
      </strong>
      <%= @composition.name %>
      <hr>
      <strong>
        <%= model_class.human_attribute_name(:type_residue) %>:
      </strong>

      <%= link_to_modal @composition.type_residue.name, raw_material_path(@composition.type_residue), class: "text-dark" %>
      <hr>
      <strong>
        <%= model_class.human_attribute_name(:compositional) %>s:
      </strong>
      <ul>
        <% @composition.raw_materials.each do |raw_material| %>
          <li>
            <%= link_to_modal raw_material.name, raw_material_path(raw_material), class: "text-dark" %>
          </li>
        <% end %>
      </ul>
      <hr>
    </p>
  </div>
</div>