config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  resources :category_products
  resources :bill_receivables
  resources :bill_payables
  resources :provider_contracts
  resources :banks
  resources :cred_cards
  resources :revenues
  resources :categories
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :transfers, except: %i[edit update]

  # resources :out_of_stocks
  resources :delivery_options
  resources :type_of_payments
  resources :products
  resources :budgets
  resources :hits
  resources :providers
  resources :clients
  resources :employees
  resources :stock_raw_materials, except: %i[edit update]
  resources :stock_final_products
  resources :compositions
  resources :raw_materials

  # client_product_custom
  get '/clients/:id/create_product_customs', to: 'clients#create_product_customs'
  get '/clients/:id/product_customs', to: 'clients#list_product_customs'
  put '/clients/:id/product_customs_update', to: 'clients#update_list_product_customs'

  # credito / debito
  get '/bank/credit_or_debit/:id', to: 'banks#credit_or_debit', as: :credit_or_debit
  post '/bank/credit_or_debit/:id', to: 'banks#credit_or_debit_update', as: :credit_or_debit_update

  # contas a receber
  put '/contas_a_receber/item/receber/:item_id', to: 'bill_receivables#receive_item_update', as: :receive_item_update
  get '/contas_a_receber/item/receber/:item_id', to: 'bill_receivables#receive_item', as: :receive_item

  post '/contas_a_receber/receber_itens', to: 'bill_receivables#receives', as: :receives
  put '/contas_a_receber/receber_itens', to: 'bill_receivables#receives_update', as: :receives_update

  # contas a pagar
  get '/payment/excel/', to: 'bill_payables#payment_excel', as: :excel
  put '/contas_a_pagar/item/pagar/:item_id', to: 'bill_payables#pay_item_update', as: :pay_item_update
  get '/contas_a_pagar/item/pagar/:item_id', to: 'bill_payables#pay_item', as: :pay_item

  post '/contas_a_pagar/paga_itens', to: 'bill_payables#pays', as: :pays
  put '/contas_a_pagar/paga_itens', to: 'bill_payables#pays_update', as: :pays_update

  get '/product/cod/:cod', to: 'products#product_cod', as: :product_cod

  put '/reserve_product/:id' => 'budgets#updated_reserve_product', as: :reserve_product

  get '/reserve_all_budget/:id' => 'budgets#reserve_all_budget', as: :reserve_all_budget

  scope '/relatorio' do
    get '/producao-diaria' => 'reports#daily_production', as: :daily_production
  end

  scope '/busca' do
    get '/endereco/:cep', to: 'home#find_by_address'
    get '/cidades/:id', to: 'home#find_city'
    get '/sub-item-entrega/:id', to: 'home#find_delivery'
    get '/sub-item-pagamento/:id', to: 'home#find_payment'
    get '/batida/:id', to: 'home#find_hit'
    get '/produto-primitivo/:id', to: 'home#produto_primitivo'
  end

  scope '/pedido' do
    get '/reserve_product/:id', to: 'budgets#reserve_product'
    get '/pdf/:id', to: 'budgets#budget_pdf', as: :budget_pdf
    get '/orderm-de-servico/:id', to: 'budgets#order_service', as: :order_service
    get '/atualiza-status/:id/:status', to: 'budgets#update_status', as: :budget_update_status
    post '/atualiza-status/', to: 'budgets#update_status', as: :budget_update_status_obs
  end

  get '/load_hit_items/:composition', to: 'hits#load_items'
  get '/find_product/:id', to: 'budgets#find_product'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  authorize_resource class: false

  def index
    order_by = "products.name asc"
    merge_where = {status: 2}

    @products = Product.left_joins(budget_products: [:budget]).where(budgets: merge_where).select("array_agg(distinct(budgets.id)) as budgets_ids, sum(budget_products.qnt) as qnt_pedidos", "(sum(budget_products.qnt) - products.qnt) as para_produzir", "count(budget_products.product_id) as total_produto", "products.*").group("budget_products.product_id", "products.id", "products.name", "products.cod").having("(sum(budget_products.qnt) - products.qnt) > ?", 0).order(order_by)

    @modal_size = 'lg'

    @bill_payables = BillPayable.includes(:provider_contract).where(status: [0,1]).accessible_by(current_ability).order(id: :desc).limit(20)
  end

  def find_by_address
    api = CorreiosECT::Api.new
    address = api.consulta_cep params[:cep]
    unless address.present?
      address_full = 0
    else
      state = State.where(acronym: address["uf"]).first
      city = City.where(name: address["cidade"]).first
      cities = City.where(state_id: state.id).select(:id, :name).order(:name)
      address_full = {bairro: address["bairro"], cep: address["cep"], city: city.id, street: address["end"], id: address["id"], state: state.id, cities: cities }
    end
    render :json => address_full
  end

  def find_city
    cities = City.where(state_id: params[:id]).select(:id, :name).order(:name)

    render json: cities
  end

  def find_hit
    hit = Hit.find(params[:id]).hit_items.sum(:weight).round(2)

    render json: hit
  end

  def produto_primitivo
    qnt = Product.find(params[:id]).qnt.round(2)

    render json: qnt
  end

  def find_payment
    payments = SubTypePayment.where(type_of_payment_id: params[:id]).select(:id, :name).order(:name)

    render json: payments
  end

  def find_delivery
    deliveries = SubDeliveryOption.where(delivery_option_id: params[:id]).select(:id, :name).order(:name)

    render json: deliveries
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="col-xl-6 col">
    <h2 class="text-center">
      Contas a pagar
    </h2>
    <%- model_class = BillPayable -%>
    <table class="table table-bordered table-hover text-center">
      <thead class="thead-light">
        <tr>
          <th scope="col"><%= "#" %></th>
          <th scope="col"><%= model_class.human_attribute_name(:provider_contract) %></th>
          <th scope="col"><%= model_class.human_attribute_name(:status) %></th>
          <th scope="col"><%= model_class.human_attribute_name(:total_value) %></th>
          <th scope="col"><%= model_class.human_attribute_name(:due_date) %></th>
          <th scope="col" class="d-print-none text-center"><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>

      <tbody>
        <% @bill_payables.each do |bill_payable| %>
          <tr id="bill_payable-item-<% bill_payable.id %>">
            <td scope="row"><%= link_to bill_payable.id, bill_payable %></td>
            <td><%= link_to_modal bill_payable.provider_contract.name, provider_contract_path(bill_payable.provider_contract), class: 'text-dark' %></td>
            <td><%= label_status_bp bill_payable %></td>
            <td><%= number_to_currency bill_payable.total_value %></td>
            <td><%= bill_payable.status != 'paid' ? bill_payable.due_date : '-' %></td>
            <% pays = bill_payable.bill_payable_installments.where(status: 0).order(:date) %>
            <% pay = pays.first if pays.present? %>

            <td class="d-print-none text-center">
              <%= link_to "Pagar", pay_item_path(pay), class: 'btn btn-outline-success' if pays.present? %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-xl-6 col  border-left border-light">
    <h2 class="text-center">
      Produção
    </h2>
    <%- model_class = Product -%>
    <table class="table table-striped text-center table-bordered">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col"><%= model_class.human_attribute_name(:cod) %></th>
          <th scope="col"><%= model_class.human_attribute_name(:name) %></th>
          <!-- <th scope="col">Pedidos</th> -->
          <th scope="col" class="d-print-none"><%= "Em Estoque" %></th>
          <th scope="col" class="d-print-none"><%= "Esperado" %></th>
          <th scope="col"><%= "Para Produzir" %></th>
        </tr>
      </thead>
      <tbody>
        <% @products.each_with_index do |product, i| %>
            <tr>
              <th scope="row"><%= i+1 %></th>
              <th scope="row"><%= product.cod %></th>
              <td><%= link_to_modal product.name, product_path(product.id), class: 'text-dark' %></td>
             <!--  <th scope="row">
                <ul class="text-left">
                  <% product.budgets_ids.each_with_index do |single, i| %>
                    <%= i%4 == 0 ? '<li>'.html_safe : '' %>
                      <%= link_to_modal Budget.find(single).cod_name, budget_path(single) %>
                    <%= i%4 == 3 ? '</li>'.html_safe : ',' %>
                  <% end %>
                </ul>
              </th> -->
              <td style="background-color: #c5ffe5 " class="d-print-none"><%= number_with_delimiter product.qnt.to_i, delimiter: ".", separator: "," %> itens</td>
              <td style="background-color: #fbffa2 " class="d-print-none"><%= number_with_delimiter product.qnt_pedidos.to_i, delimiter: ".", separator: "," %> itens</td>
              <td style="background-color: #ff9ea0 "><%= number_with_delimiter product.para_produzir.to_i, delimiter: ".", separator: "," %> itens</td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>