config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  resources :category_products
  resources :bill_receivables
  resources :bill_payables
  resources :provider_contracts
  resources :banks
  resources :cred_cards
  resources :revenues
  resources :categories
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :transfers, except: %i[edit update]

  # resources :out_of_stocks
  resources :delivery_options
  resources :type_of_payments
  resources :products
  resources :budgets
  resources :hits
  resources :providers
  resources :clients
  resources :employees
  resources :stock_raw_materials, except: %i[edit update]
  resources :stock_final_products
  resources :compositions
  resources :raw_materials

  # client_product_custom
  get '/clients/:id/create_product_customs', to: 'clients#create_product_customs'
  get '/clients/:id/product_customs', to: 'clients#list_product_customs'
  put '/clients/:id/product_customs_update', to: 'clients#update_list_product_customs'

  # credito / debito
  get '/bank/credit_or_debit/:id', to: 'banks#credit_or_debit', as: :credit_or_debit
  post '/bank/credit_or_debit/:id', to: 'banks#credit_or_debit_update', as: :credit_or_debit_update

  # contas a receber
  put '/contas_a_receber/item/receber/:item_id', to: 'bill_receivables#receive_item_update', as: :receive_item_update
  get '/contas_a_receber/item/receber/:item_id', to: 'bill_receivables#receive_item', as: :receive_item

  post '/contas_a_receber/receber_itens', to: 'bill_receivables#receives', as: :receives
  put '/contas_a_receber/receber_itens', to: 'bill_receivables#receives_update', as: :receives_update

  # contas a pagar
  get '/payment/excel/', to: 'bill_payables#payment_excel', as: :excel
  put '/contas_a_pagar/item/pagar/:item_id', to: 'bill_payables#pay_item_update', as: :pay_item_update
  get '/contas_a_pagar/item/pagar/:item_id', to: 'bill_payables#pay_item', as: :pay_item

  post '/contas_a_pagar/paga_itens', to: 'bill_payables#pays', as: :pays
  put '/contas_a_pagar/paga_itens', to: 'bill_payables#pays_update', as: :pays_update

  get '/product/cod/:cod', to: 'products#product_cod', as: :product_cod

  put '/reserve_product/:id' => 'budgets#updated_reserve_product', as: :reserve_product

  get '/reserve_all_budget/:id' => 'budgets#reserve_all_budget', as: :reserve_all_budget

  scope '/relatorio' do
    get '/producao-diaria' => 'reports#daily_production', as: :daily_production
  end

  scope '/busca' do
    get '/endereco/:cep', to: 'home#find_by_address'
    get '/cidades/:id', to: 'home#find_city'
    get '/sub-item-entrega/:id', to: 'home#find_delivery'
    get '/sub-item-pagamento/:id', to: 'home#find_payment'
    get '/batida/:id', to: 'home#find_hit'
    get '/produto-primitivo/:id', to: 'home#produto_primitivo'
  end

  scope '/pedido' do
    get '/reserve_product/:id', to: 'budgets#reserve_product'
    get '/pdf/:id', to: 'budgets#budget_pdf', as: :budget_pdf
    get '/orderm-de-servico/:id', to: 'budgets#order_service', as: :order_service
    get '/atualiza-status/:id/:status', to: 'budgets#update_status', as: :budget_update_status
    post '/atualiza-status/', to: 'budgets#update_status', as: :budget_update_status_obs
  end

  get '/load_hit_items/:composition', to: 'hits#load_items'
  get '/find_product/:id', to: 'budgets#find_product'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  root to: 'home#index'
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  authorize_resource class: false

  def daily_production

    order_by = "products.name asc"
    @employee = nil
    @client = nil
    merge_where = {status: 2}

    if params[:q]
      if params[:q][:s]
        order_by = params[:q][:s]
      end
      @employee = params[:q][:budget_products_budget_employee_id_in].drop(1)
      @client = params[:q][:budget_products_budget_client_id_in].drop(1)
      params[:q][:budget_products_budget_employee_id_in] = ''
      params[:q][:budget_products_budget_client_id_in] = ''
    end

    @q = Product.ransack(params[:q])

    if @client.present?
      merge_where[:client_id] = @client
    end
    if @employee.present?
      merge_where[:employee_id] = @employee
    end


    @products = @q.result.left_joins(budget_products: [:budget]).where(budgets: merge_where).select("array_agg(distinct(budgets.id)) as budgets_ids, sum(budget_products.qnt) as qnt_pedidos", "(sum(budget_products.qnt) - products.qnt) as para_produzir", "count(budget_products.product_id) as total_produto", "products.*").group("budget_products.product_id", "products.id", "products.name", "products.cod").having("(sum(budget_products.qnt) - products.qnt) > ?", 0).order(order_by)
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/daily_production.html.erb
<div class="page-header d-flex justify-content-lg-between align-items-center">
  <h1>Previsão de produção do dia</h1>
</div>

<%- model_class = Budget -%>
<%= search_form_for @q, url: daily_production_path, html: { class: 'form-horizonal d-print-none' } do |f| %>
  <h3>Busca</h3>
  <div class="row justify-content-md-center">
    <div class="col-4">
      <%= f.input :cod_cont, label: "Código do Produto", placeholder: 'Ex: TS20', required: false %>
      <%= f.input :budget_products_budget_id_in, label: model_class.human_attribute_name(:cod_name), as: :select, :collection => Budget.where(status: 2).order(:cod_name).map { |e| [e.cod_name, e.id] }, input_html: {class: 'multi-select2', multiple: true}, required: false %>

    </div>
    <div class="col-4">
      <%#= f.input :budget_products_budget_created_at_gteq, label: "#{model_class.human_attribute_name(:created_at)} inicial", as: :string, placeholder: 'Ex: 10/01/2018', required: false, input_html: { class: 'date datepicker-here', data: { language: 'pt-BR'} } %>
      <%#= f.input :budget_products_budget_created_at_lteq, label: "#{model_class.human_attribute_name(:created_at)} final", as: :string, placeholder: 'Ex: 10/02/2018', required: false, input_html: { class: 'date datepicker-here', data: { language: 'pt-BR'} } %>
      <%= f.input :budget_products_budget_client_id_in, label: model_class.human_attribute_name(:client), as: :select, :collection => Client.where(id: Budget.where(status: 2).pluck(:client_id).uniq).order(:company_name).map { |e| [e.company_name, e.id] }, selected: @client, input_html: {class: 'multi-select2', multiple: true}, required: false %>
      <%= f.input :budget_products_budget_employee_id_in, label: model_class.human_attribute_name(:employee), :as => :select, :collection => Employee.where(id: Budget.where(status: 2).pluck(:employee_id).uniq).order(:name).map { |e| [e.name, e.id] }, selected: @employee, input_html: {class: 'multi-select2', multiple: true}, required: false %>
    </div>
    <div class="col-4">
      <%#= f.input :budget_products_budget_deadline_gteq, label: "#{model_class.human_attribute_name(:deadline)} inicial", as: :string, placeholder: 'Ex: 10/01/2018', required: false, input_html: { class: 'date datepicker-here', data: { language: 'pt-BR'} } %>
      <%#= f.input :budget_products_budget_deadline_lteq, label: "#{model_class.human_attribute_name(:deadline)} final", as: :string, placeholder: 'Ex: 10/02/2018', required: false, input_html: { class: 'date datepicker-here', data: { language: 'pt-BR'} } %>
    </div>
    <%= f.button :submit, class: 'btn btn-success' %>
    <%= link_to 'Limpar', daily_production_path, class: 'btn btn-info ml-3' %>
  </div>
  <hr>
<% end %>

<%- model_class = Product -%>
<table class="table table-striped text-center table-bordered">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col"><%= sort_link @q, :cod, model_class.human_attribute_name(:cod), default_order: :desc %></th>
      <th scope="col"><%= sort_link @q, :name, model_class.human_attribute_name(:name), default_order: :desc %></th>
      <th scope="col">Pedidos</th>
      <th scope="col" class="d-print-none"><%= sort_link @q, :qnt, "Em Estoque", default_order: :desc %></th>
      <th scope="col" class="d-print-none"><%= sort_link @q, :qnt_pedidos, "Esperado", default_order: :desc %></th>
      <th scope="col"><%= sort_link @q, :para_produzir, "Para Produzir", default_order: :desc %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each_with_index do |product, i| %>
        <tr>
          <th scope="row"><%= i+1 %></th>
          <th scope="row"><%= product.cod %></th>
          <td><%= link_to_modal product.name, product_path(product.id), class: 'text-dark' %></td>
          <th scope="row">
            <ul class="text-left">
              <% product.budgets_ids.each_with_index do |single, i| %>
                <%= i%4 == 0 ? '<li>'.html_safe : '' %>
                  <%= link_to_modal Budget.find(single).cod_name, budget_path(single) %>
                <%= i%4 == 3 ? '</li>'.html_safe : ',' %>
              <% end %>
            </ul>
          </th>
          <td style="background-color: #c5ffe5 " class="d-print-none"><%= number_with_delimiter product.qnt.to_i, delimiter: ".", separator: "," %> itens</td>
          <td style="background-color: #fbffa2 " class="d-print-none"><%= number_with_delimiter product.qnt_pedidos.to_i, delimiter: ".", separator: "," %> itens</td>
          <td style="background-color: #ff9ea0 "><%= number_with_delimiter product.para_produzir.to_i, delimiter: ".", separator: "," %> itens</td>
        </tr>
    <% end %>
  </tbody>
</table>